# Site settings
title: robot.wtf
description: blog about robots, wtf
url: "https://robot.wtf"
baseurl: ""

# Author settings
author: Schuyler Erle

# Beautiful Jekyll theme settings
navbar-links:
  About: "about"

# Avatar / profile picture
# avatar: "/assets/img/avatar.jpg"

# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

# GitHub Pages settings
domain: robot.wtf

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
